### ISSUE TITLE
설치시 오류가 뜹니다

### ISSUE THREAD

**Issue by 4e55** [devhotteok/TwitchLink#10]
윈도우7 사용중이고, 예전에는 설치 잘 되다가 최근에 다시 설치하니 아래와 같은 오류가 뜨면서 프로그램 진입이 막힙니다.

1. 컴퓨터에 api-ms-win-core-path-l1-1-0.dll이 없어 프로그램을 시작 할 수 없습니다.

2. Error loading Python DLL 'C:\~프로그램경로\python39.dll' LoadLibrary : 지정된 모듈을 찾을수 없습니다.

파이썬 3.9 이상의 버전이 윈도우7 지원을 종료하면서 발생하는 문제같은데 혹시 파이썬버전을 3.8버전으로 낮춘 프로그램을 제작해주실 수 있으신가요?

**Comment by devhotteok** [comment]
Sorry, TwitchLink only supports Windows 10 or higher.
