### ISSUE TITLE
still having the same problem of scheduled downloading

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#101]
#68
#81 

I want to attach a log file, where can I find log file?

There is no logfile in the twitchlink folder and download folder on drive c.

**Comment by Dev-Pixel-www** [comment]
If your browser or Chrome has the ad blocking plug-in installed, try disabling or uninstalling it.

note : https://addplus.tistory.com/entry/%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0-%ED%8A%B8%EC%9C%84%EC%B9%98Twitch-%EB%AC%B4%ED%95%9C-%EB%A1%9C%EB%94%A9%EB%AC%B4%ED%95%9C-%EB%B2%84%ED%8D%BC%EB%A7%81-%ED%95%B4%EA%B2%B0%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-%EA%B4%91%EA%B3%A0-%EC%B0%A8%EB%8B%A8%EC%A0%9C%EA%B1%B0

**Comment by gtskks** [comment]
당신의 링크와는 전혀 다른 문제입니다.
로딩문제가 아니라 녹화가 멈추는게 문제입니다.

**Comment by gtskks** [comment]
> Dev



> If your browser or Chrome has the ad blocking plug-in installed, try disabling or uninstalling it.
> 
> There is an article that says that a user has solved the problem by disabling the ad blocking plug-in.
> 
> note : https://addplus.tistory.com/entry/%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0-%ED%8A%B8%EC%9C%84%EC%B9%98Twitch-%EB%AC%B4%ED%95%9C-%EB%A1%9C%EB%94%A9%EB%AC%B4%ED%95%9C-%EB%B2%84%ED%8D%BC%EB%A7%81-%ED%95%B4%EA%B2%B0%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-%EA%B4%91%EA%B3%A0-%EC%B0%A8%EB%8B%A8%EC%A0%9C%EA%B1%B0


It's a completely different issue than your link.
It's not a loading problem, it's the recording stopping.

**Comment by devhotteok** [comment]
Closed due to internal changes in fb781c56d915871feb3561b2fc4f9a42046327af
