### ISSUE TITLE
I can't login with my twitch account .

### ISSUE THREAD

**Issue by armandebreli** [devhotteok/TwitchLink#102]
After the new uptade , i can't login and connect my twitch account to the twitchlink. When i clicked the login button new tab opens but page won't load. I tried re-installing the program.  Where is the problem? Thanks.

**Comment by Dev-Pixel-www** [comment]
Are you using VPN?

**Comment by armandebreli** [comment]
> 

I don't use any  vpn .

**Comment by devhotteok** [comment]
Closed due to inactivity.
