### ISSUE TITLE
Forcibly terminated the app during the download.

### ISSUE THREAD

**Issue by WhoKnowthat** [devhotteok/TwitchLink#104]
실시간 다운중 중지버튼을 누르지않고
프로그램을 종료하면서 중지될경우
그때까지 저장한 영상은 재생되지않는데
해결방법이 있나요

**Comment by devhotteok** [comment]
Unfortunately, no.

**Comment by kchwan1218** [comment]
TS 로 저장 하면 해결됩니다. MP4 로 저장시 재생이 안됩니다.
