### ISSUE TITLE
Can't maximize TwitchLink

### ISSUE THREAD

**Issue by LuckramK** [devhotteok/TwitchLink#107]
I couldn't maximize the app, It was working just fine but then I saw that the app was minimized, I tried to maximized it to see the downloads and it did nothing. I looked into the Task Manager and it said that the app was working just fine, it never showed a message saying that the app "was not working" or anything at all. I left it like that, waiting to see if after some time it would work again and after like an hour I tried to find it in the Task Manager and the app just disappeared from there, but looks like is still working. Losing hope that the app would respond again I had to close it from the taskbar and that was the only moment when the app did something, it showed a message saying that I had downloads in progress and asking If I was sure about close it.

**Comment by devhotteok** [comment]
Closed due to inactivity.
