### ISSUE TITLE
Clip 다운로드 시 Crash 발생

### ISSUE THREAD

**Issue by ssyonga** [devhotteok/TwitchLink#11]
1.1 버전 업데이트 이후 Clip 다운로드 시 아래와 같이 Windows에서 Crash가 발생합니다.
사용OS : Window 10 x64

오류 있는 응용 프로그램 이름: TwitchLink.exe, 버전: 0.0.0.0, 타임스탬프: 0x6017b481
오류 있는 모듈 이름: Qt5Core.dll, 버전: 5.15.2.0, 타임스탬프: 0x5fa4dd3b
예외 코드: 0xc0000409
오류 오프셋: 0x00000000000204e8
오류 있는 프로세스 ID: 0x40f8
오류 있는 응용 프로그램 시작 시간: 0x01d7ff1eff0178af
오류 있는 응용 프로그램 경로: C:\TwitchLink\TwitchLink.exe
오류 있는 모듈 경로: C:\TwitchLink\Qt5Core.dll
보고서 ID: d7adc228-7149-4cd8-9ddb-822b96da63c7
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID:

**Comment by devhotteok** [comment]
Closed with commit c7bae13b46c7e6af7dc74539fdbca9cbb01f4778
