### ISSUE TITLE
How to minimize to system tray

### ISSUE THREAD

**Issue by TBloop** [devhotteok/TwitchLink#111]
I saw in the patch notes it mentioned something about being able to minimize to system tray. However, when I press minimize, it goes to my taskbar like normal, and pressing the X just closes the program. Neither one puts it into the system tray. 

I'm using Windows 11 Pro, 22H2. Something that may be relevant is that I use Explorerpatcher which is a program to make your start menu like windows 10. It hasnt ever affected the behavior of other programs though.

**Comment by devhotteok** [comment]
Try the following.
Settings > General > When closing window > Minimize to system tray
