### ISSUE TITLE
3.0.0 can't log in twitch turbo account

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#113]
After upgrading to 3.0 When I enter my account and password, I still get the login screen.

**Comment by kingpopcorn17** [comment]
I have the same issue as well

**Comment by sample7687** [comment]
I have the same issue

**Comment by Yunhyuk-Jeong** [comment]
The same problem is happening to me.

**Comment by devhotteok** [comment]
Closed with commit eea74ff1c34f8816fdaa0c584e5031835136764a
