### ISSUE TITLE
NEVER force an update while its running.

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#117]
Please never force an update to make the app work, If you are not home when it happens the scheduled streams will fail to download.

**Comment by devhotteok** [comment]
Updates will not be enforced, except in cases where previous versions are non-functional due to breaking changes.

**Comment by skyfox1977** [comment]
Well, it is forced since it is no longer possible to use old version, and new 3.0.1 is crashing/unusable. At least version 2.4.0 worked without crashing.
