### ISSUE TITLE
Crash on 3.0.1

### ISSUE THREAD

**Issue by smdkdkdk** [devhotteok/TwitchLink#119]
실시간 녹화를 하고있으면 프로그램이 충돌났다면서 간헐적으로 갑자기 프로그램이 꺼집니다.
로그인 안되는 이슈는 명확했는데, 이건 이유를 도저히 모르겠네요

**Comment by devhotteok** [comment]
Try to describe the problem as detailed as possible.
Provide as much information about the problem as possible.
Please attach the log file with the issue.

**Comment by devhotteok** [comment]
Additionally, this might be the same issue as the already fixed #124
Please refer to that issue.
