### ISSUE TITLE
Windows 11 error

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#120]
Not sure if it goes here but I can't run TwitchLink in Windows 11.
Simply doesn't open.

**Comment by devhotteok** [comment]
Try to describe the problem as detailed as possible.
Provide as much information about the problem as possible.
Please attach the log file with the issue.

**Comment by nameless01234567** [comment]
If I click on open TwitchLink it will appear as a process on the Task Manager for a second or so and then disappear as if it had closed.
There's no log file since it doesn't even open the program for a more formal error to occur.

**Comment by devhotteok** [comment]
It seems that the program has not been installed properly. Some antivirus programs can cause such results.

**Comment by nameless01234567** [comment]
Figured out, it was a conflict with a entirely different program.
