### ISSUE TITLE
The file has been split into multiple pieces.

### ISSUE THREAD

**Issue by kchwan1218** [devhotteok/TwitchLink#123]
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/97836410-e0b9-4c20-9b29-b37d612bf0b5)

**Comment by devhotteok** [comment]
Try to describe the problem as detailed as possible.
Provide as much information about the problem as possible.
Please attach the log file with the issue.

Additionally, this can also happen if your network is unstable or your hardware device's performance is insufficient.

**Comment by kchwan1218** [comment]
> Try to describe the problem as detailed as possible. Provide as much information about the problem as possible. Please attach the log file with the issue.
> 
> Additionally, this can also happen if your network is unstable or your hardware device's performance is insufficient.

i aleady attach log file other issue
please close this issue
