### ISSUE TITLE
RuntimeError due to QNetworkReply

### ISSUE THREAD

**Issue by kawaikami1** [devhotteok/TwitchLink#124]
3.0.1 버젼에서 프로그램 실행시 주기적으로 다운되고 오류로그가 표시 됩니다. 다른 분들은 그런지 모르겠으나 저 같은 경우 wrapped c/c++ object of type qnetworkreplay has been deleted 오류 로그와 함께 오류 로그 파일이 형성됩니다. 해당 문제를 해결하려면 어떻게 해야 할까요?

**Comment by devhotteok** [comment]
Closed with commit 9ce07f297808de1ffbb6bb2901426228e496fe3d
