### ISSUE TITLE
RuntimeError due to QNetworkReply

### ISSUE THREAD

**Issue by kchwan1218** [devhotteok/TwitchLink#125]
[TwitchLink_2023.08.21_10-43-33#8c924a62-7972-46e2-ad89-13b7d247f39d.log](https://github.com/devhotteok/TwitchLink/files/12397097/TwitchLink_2023.08.21_10-43-33.8c924a62-7972-46e2-ad89-13b7d247f39d.log)

이 프로그램으로 스트리머 다시보기 올려주는 작업 하고있는데 
파일 분할 된건 자르고 붙이고 인코딩 하면 되는데
프로그램이 꺼져버려서 자르고 이어 붙일부분이 아예 꺼져버리는 바람에 다운 못받아서 
해당 작업도 못하게 되어서 
제 신뢰도가 깎이는 문제가 발생했네요

**Comment by devhotteok** [comment]
Duplicate of #124
