### ISSUE TITLE
Network folders are not available.

### ISSUE THREAD

**Issue by km647777** [devhotteok/TwitchLink#127]
PC 하드로 저장하는 데에는 무리가 있어 NAS를 이용하여 2.4.0 버전까지는 네트워크 폴더로 연결하여 이용하고 있었습니다.
(예 : 네트워크 드라이브 추가를 통해 NAS 드라이브를 생성 후, 연결하여 사용)
3.0.1 버전으로 업데이트 된 이후 네트워크 폴더가 연결되어 있음에도 불구하고, 관리자 권한으로 실행 시 네트워크 드라이브가 보이지 않고, 그냥 실행했을 경우 네트워크 드라이브는 보이지만, 설정 적용 시 예기치 못한 오류라는 문구가 표시되며 작동이 되지 않습니다.

로컬인 C나 D드라이브에 경로 지정 시 원활하게 작동되지만, 그 외 경로는 막힌 것 같습니다...

**Comment by devhotteok** [comment]
Try to describe the problem as detailed as possible.
Provide as much information about the problem as possible.
Please attach the log file with the issue.

Also, this can be caused by permission issues on the network storage.

**Comment by MartynHolland-nl** [comment]
Copying in my log again after mine was merged
[TwitchLink_Download_2023.08.22_15-26-45#ae22ce29-0982-47a9-8b2b-1ea8068f1e2e.log](https://github.com/devhotteok/TwitchLink/files/12410396/TwitchLink_Download_2023.08.22_15-26-45.ae22ce29-0982-47a9-8b2b-1ea8068f1e2e.log)

**Comment by devhotteok** [comment]
Closed with commit 7236857f9e2f26f01b67de1f93cac9b86b215b44

**Comment by kchwan1218** [comment]
3.1.0 에서 해결 되었습니다.
시도 해보세요~
