### ISSUE TITLE
3.0 업그레이드 후 문제점

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#129]
1. 예약다운로드기능으로 녹화중에 정지됐다가 다시 녹화되는 현상발생중 (문제없이 녹화되는 경우도있음)

2. 녹화손실여부를 어디서 확인하는지 알수없음

강제로 업데이트 버전을 쓰도록하는게 좀 불편하네요

안정화될때까지는 이전버전도 사용할수있게끔 개선부탁드립니다.

프로그램은 항상 감사하게 잘 사용하고있습니다.

**Comment by ynazazaaaaa** [comment]
강제 업데이트버전 저도 불편하네요

**Comment by devhotteok** [comment]
1. Duplicate of #124
2. Duplicate of #118
