### ISSUE TITLE
An unexpected error occurred while connecting to the server.

### ISSUE THREAD

**Issue by ynazazaaaaa** [devhotteok/TwitchLink#131]
서버와 연결 중 예기치 못한 오류가 발생하였습니다.
잠시 후 다시 시도하세요. 

라고뜨고 프로그램 강제종료됩니다. 급할때 이전버전이라도 쓰고싶은데, 강제 버전업데이트도 불편해요

**Comment by sample7687** [comment]
저도 동일한 문제가 발생중인데 이유를 알수가없네요ㅠ

**Comment by devhotteok** [comment]
Closed with commit 9ce07f297808de1ffbb6bb2901426228e496fe3d
