### ISSUE TITLE
Please roll back to 2.4.0 too many bugs in 3.0.1

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#132]
New version is very unreliable.

"An unexpected error occurred while connecting to the server.
Some features will be disabled.
Please restart the app."

**Comment by nameless01234567** [comment]
I second this, I've only completed one 2h download after errors (that I never encountered prior), usually downloads don't pass the 2h mark though.

**Comment by Adache00** [comment]
You guys are lucky to even get that far, I can't even get it to run, get a load of error codes on launch and it triggers my antivirus. Even if I add it as an exception, I still get errors relating to .PYS files.
