### ISSUE TITLE
Unhandled exception in script , Failed to excute script 'TwitchLink' due to unhandled excepation : DLL load faild while importing QtGul

### ISSUE THREAD

**Issue by faroilj** [devhotteok/TwitchLink#134]
![트위치링크실행안됨](https://github.com/devhotteok/TwitchLink/assets/142883650/7a57e12d-4aa9-4db4-94a8-39d55aa47246)

The above message appears,
Is there a program or extension that I didn't install?
How can I solve this problem?
I appreciate your help.

**Comment by devhotteok** [comment]
TwitchLink only supports Windows 10 and higher.
Make sure you are using these operating systems.
