### ISSUE TITLE
TwitchLink has crashed due to an unexpected error.

### ISSUE THREAD

**Issue by scweeny** [devhotteok/TwitchLink#136]
에러 로그 포함드립니다.

[TwitchLink_2023.08.22_10-31-13#91d29027-4ba8-45ac-8d47-77a3fb291e40.log](https://github.com/devhotteok/TwitchLink/files/12408112/TwitchLink_2023.08.22_10-31-13.91d29027-4ba8-45ac-8d47-77a3fb291e40.log)

**Comment by kchwan1218** [comment]
설치 후 처음 뜨는 공지사항에 나와있다시피 2.4.0도 이용 가능 하십니다. 삭제 후 재 설치 하시면 실행 될겁니다

**Comment by scweeny** [comment]
> 설치 후 처음 뜨는 공지사항에 나와있다시피 2.4.0도 이용 가능 하십니다. 삭제 후 재 설치 하시면 실행 될겁니다

아 감사합니다.

**Comment by devhotteok** [comment]
Closed with commit 33b938cdc56453c7f674ffeabc0090a3a4f46bb9
