### ISSUE TITLE
stipulation unstable network connection and file divide 

### ISSUE THREAD

**Issue by kchwan1218** [devhotteok/TwitchLink#137]
어디사심.. 한국인 이십니까 외국인 이십니까??
where are you stay?

i guessing many korean is using VPN 
because twitch didn't suport 1080P

i think, sone VPN client make unstable network connection status.  

twitchlink 3.0.2 fine working at normal connection.
but that's abnormal working in VPN Connectioning

when abnormal status displayied this notification
![image](https://github.com/devhotteok/TwitchLink/assets/38702357/dabd2b5b-c112-4e29-b0c1-e55096f5ea34)

**Comment by devhotteok** [comment]
Closed with commit 33b938cdc56453c7f674ffeabc0090a3a4f46bb9
