### ISSUE TITLE
음소거 해제 기능이 동작하지 않습니다.

### ISSUE THREAD

**Issue by devking85** [devhotteok/TwitchLink#14]
# 음소거 해제 기능 실패

## 개요
- `1.1.1` 버전에서 확인하였습니다.
- `1.1.0` 과 `1.1.1` 의 업데이트 간격이 짧아서, 어느 버전부터 문제가 발생했는지 모르겠습니다.
- `1.0.4` 버전으로 회귀해서 영상의 음소거 영역에 대한 해제 테스트 해보려고 했으나, 필수 업데이트 알림에 의해서 테스트 해보지 못했습니다.
- **트위치 사이트 다시보기 플레이어**의 타임라인에 표시되는 음소거 영역과 동일한 지점임을 확인했습니다.

## 동작 당시의 조건

`1.1.1` 버전의 동작 당시 조건은 다음과 같습니다.

- 스트리머는 방송을 종료한 상태였습니다. 
- 다음 두 가지 시도 모두 **음소거 해제**가 동작하지 않았습니다.
    - 방송이 종료된 후 5분 뒤 시도했습니다.
    - 방송이 종료된 후 1일 뒤 시도했습니다.
- **음소거 해제** 기능은 활성(체크)된 상태였습니다.
- TwitchLink 외 다른 프로그램은 과도하게 네트워크 대역폭을 점유하지 않았습니다.
- 그 외 다른 설정은 모두 기본 값입니다. 프로그램 설치 후 **고급 설정을 건드리지 않았습니다.**

**Comment by devking85** [comment]
수정하시는 동안, 가능하다면 구 버전 사용을 할 수 있도록 해주셨으면 합니다. 감사합니다.

**Comment by devhotteok** [comment]
The unmute feature does not guarantee a 100% success rate.
This function only recovers the original as much as possible.
To avoid this problem, I recommend that you use the live download feature or download the video with the update tracking settings.

**Comment by devhotteok** [comment]
Duplicate of #3
