### ISSUE TITLE
Subprocess related bugs

### ISSUE THREAD

**Issue by mic219** [devhotteok/TwitchLink#142]
TwitchLink has crashed due to an unexpected error.
If this happens frequently, please attach the following log file and report it to us.

File: C:/Users/AppData/Local/Temp/TwitchLink/TwitchLink_2023.08.25_19-55-35#636fd0dd-f4e3-45ae-bc57-b712bb3bff3c.log

**Comment by devhotteok** [comment]
Please attach the actual file, not the name.

**Comment by kchwan1218** [comment]
한번에 22개 방송 다운받으시면 괜찮아요?ㄷㄷㄷ

**Comment by devhotteok** [comment]
Closed with commit 0031e1a9da79792f2596a27afda0c0dfd890fdf0
