### ISSUE TITLE
TwichLink crashes when I change my monitor. 모니터 바꿀 때 죽어요

### ISSUE THREAD

**Issue by Andal122** [devhotteok/TwitchLink#143]
_**For TwitchLink 3.1.0,**_
I don't know the exact reasone of the bug but when i change my monitor, the program doesn't work.
I am using one amongst the desktop monitor or beam projector (two dispaly is not used simultaneously). The desktop monitor has 1080 resolution and the beam projector is 720 one. When i change my display from desktop monitor to beam projector, the size of the program is keeped in 1080 (that means, the right side and lower side is not displayed in my beam projector) and any botton is unavailbale. So only i can do is exit the program. Similarly, when i changemy display from beam projector to monitor, the size of the program is keeped in 720 (the right side and lower side shows black) and no botton is available. 
So i cant change my display when a video is on download.

Thank you.

(In Korean)
버전 3.1.0부터 문제인거같습니다. 3.0.2였나.. 이거 쓸때는 괜찮았어요. 
제가 영어가 부드럽지도 않고 개발자님 한국분이신거같아서 한국말로도 쓸게요..
이유는 정확히 모르겠습니다만 모니터 화면 바꿀 때 프로그램이 죽습니다. 
제가 1080짜리 모니터 아니면 720짜리 빔프로젝터를 번갈아가면서 씁니다 (동시에 안씀). 모니터에서 빔프로젝터로 전환하면 프로그램이 1080일 때 사이즈를 그대로 가지고 720으로 옮긴 형태로 되어서 아래 옆이 짤리고, 프로그램 자체가 아무 작동을 안합니다. 최대화 최소화 창닫기만 되는 상황입니다. 그래서 닫기 누르면 시스템트레이로최소화 되는게 아니라 프로그램 아예 꺼지고 다시 프로그램 실행하면 잘 됩니다.
또 마찬가지로 빔프로젝터에서 모니터로 바꾸면 720사이즈 그대로 보이고, 최대화하면 남은 공간은 그냥 검정색으로 보입니다. 마찬가지로 프로그램은 아무 작동을 안합니다. 껐다 키면 역시 작동은 잘 합니다.

이러다보니 다운로드중에 모니터 전환을 못하게 되어서.. 확인 부탁드립니다.

프로그램 늘 잘 쓰고 있습니다. 감사합니다.

**Comment by kchwan1218** [comment]
트위치 링크 프로그램 실행중에 
트위치링크 화면을 띄워놓고 모니터 전환을 하실 일이있으실까요???

그래픽 드라이버나 프로그램 충돌같은데요..

최소화 시켜두시고 화면 전환 하시는 방법은 어떠실까요?
동일하게 뻗나요?

**Comment by Andal122** [comment]
그래픽드라이버쪽에 문제가 있었나보네요. 혹시나해서 그래픽드라이버 업데이트 하고 트위치링크도 다시 3.1.0으로 업데이트 하고 사용해보니 문제 없네요. 감사합니다!
