### ISSUE TITLE
TwitchLink.exe not exist

### ISSUE THREAD

**Issue by Mohmotte** [devhotteok/TwitchLink#144]
I install the lastest release and in C:\Program Files\TwitchLink\TwitchLink.exe not exist

![Capture d’écran (267)](https://github.com/devhotteok/TwitchLink/assets/71752639/0e0712bb-174c-46b7-8d94-cfcecedc760a)

**Comment by devhotteok** [comment]
Duplicate of #97

**Comment by Mohmotte** [comment]
I uninstall a antivirus install by mistake and the lastest release work
