### ISSUE TITLE
24-hour+ Live Stream Download Issue

### ISSUE THREAD

**Issue by PP4M** [devhotteok/TwitchLink#145]
버전 3 업데이트 이전에는 28시간 이상 녹화가 끊김 없이 진행됐는데 업데이트 이후 24시간 이상 녹화 시 다운로드 창에는 녹화 중으로 표시되지만 실제 파일은 24시간에서 녹화가 끊겨있는 문제가 발생합니다

**Comment by devhotteok** [comment]
Please attach the log file of the download.
[Download History > View Logs]

**Comment by PP4M** [comment]
오류가 있던 방송 녹화 이후에 트위치링크를 업데이트 해서 그런지 다운로드 히스토리가 사라졌는데 혹시 따로 로그 파일이 저장되는 디렉토리가 있나요?

**Comment by PP4M** [comment]
[TwitchLink_Download_2023.08.28_14-31-06#ad718c34-0ed9-4e42-993d-f63f8bcb3294.log](https://github.com/devhotteok/TwitchLink/files/12486698/TwitchLink_Download_2023.08.28_14-31-06.ad718c34-0ed9-4e42-993d-f63f8bcb3294.log)

**Comment by devhotteok** [comment]
Closed with commit 891798b1e95d9c7aeab0f411b09ab99d8d7dc4f7
