### ISSUE TITLE
여러 개 다운로드 시, 다운로드가 정상작동이 되지 않습니다.

### ISSUE THREAD

**Issue by smdkdkdk** [devhotteok/TwitchLink#147]
다운로드 개수가 많아지면 다운로드가 멈춥니다.
제 네트워크 속도 기준으로,
2.4.0 이하 버전에서는 한번에 10~11개를 안정적으로 다운로드 할 수 있다면,
3.0.0 이후 모든 버전에서는 7개 정도의 다운로드 부터 다운로드가 불안정 해지고, 영상에 손실이 납니다.

예를 들어
1.     2.4.0 버전에선 동시에 11~12개의 생방송 다운이 가능한 환경
2.     3.0.0 이후 버전으로 현재 방송중인 10개의 방송을 3분 간격으로 하나씩 다운로드 시작
이라고 할 때,

7번째 부터 이전30초 다운로드를 진행하면서
나머지 6개 방송의 다운로드 속도가 약간 줄어들다 1분 내외로 모든 다운로드가 안정적으로 유지됩니다.
(작업관리자로 보면, 1080p60 기준 대략 한 개의 방송에 0.7~1.2MB/s 로 나옵니다. 2.4.0 버전과 3.0.0 이후 버전 모두 동일합니다.)

그러나 8번째 부터 이전 30초 다운로드를 진행할 때는
나머지 7개 방송의 다운로드 속도는 급격히 줄어들고, 모든 다운로드가 불안정 해집니다. 중지한 다음 결과 영상을 봐도, 군데군데 손실이 일어납니다.
(작업관리자로 보면, 확실히 손실이 일어난 불안정한 것들은 1080p60 기준 한 개당 0.0~0.4MB/s 로 나옵니다.)

2.4.0 이전은 안그러고 3.0 이후 버전에서 모두 그런것으로 보아,
개인적인 추측으로는 다운로드 시작시, 이전 30초 다운로드가 원인인듯 합니다만...

만약 이전 30초 다운로드가 원인이면
다운로드 시작에서만이라도 이전 30초 다운 기능의 on/off가 가능한지 여쭙고 싶고,
다른 이유면 버그 수정 부탁드립니다..
(방송 각각 이전 30초 on/off가 되면 더 좋을 것 같습니다...)

ps. 진짜 정 안되면 2.4.0 버전 지원 유지라도..

**Comment by devhotteok** [comment]
Duplicate of #157
