### ISSUE TITLE
Drive gets deactivated

### ISSUE THREAD

**Issue by Exnormalmap** [devhotteok/TwitchLink#148]
3.0.0출시 이후 네트워크 에러 및 저장경로인 d드라이브를 비활성화하는 에러가 발생합니다.

2.4.0에서는 어제까지 에러가 발생하지않았으나 오늘 3.1.2최신버전을 켜고 예약저장을 실행하자 시스템 오류를 발생시켜 2.4.0으로 롤백하였으나 네트워크에러를 지속발생시키고 있습니다.

D드라이브를 저장 기본 경로로 사용하는데 3이상의 버전 설치시 에러가 잦아 2.4.0으로 롤백시 해당 드라이브가 비활성화되어 물리적으로 재연결하여 활성화해야하는 경우가 지속되고 있습니다.

두가지의 해결방안이 있으면 안내부탁드립니다.
네트워크나 vpn의 문제라기에는 재연결 및 다른 프로그램이나 테스트시에는 문제가 없습니다.
거기에 트위치링크의 경우 시스템 문제 또는 네트워크 문제 또는 알려지지않은 오류를 바꿔가며 출력하고 있습니다.

**Comment by Exnormalmap** [comment]
3.0.0을 지우고 2.4.0으로 할때는 정상 동작합니다.

**Comment by ynazazaaaaa** [comment]
오류도 한두번이여야지. 매번이러네 

다운로드 강제중단
