### ISSUE TITLE
Show progress on taskbar

### ISSUE THREAD

**Issue by 114call** [devhotteok/TwitchLink#153]
안녕하세요.

예전에 다운로드중일때 윈도우 작업표시줄에 있는 
트위치링크 아이콘에 실시간 다운로드 바 움직이는것처럼 
아이콘에 다운로드 애니메이션이 표시 되었던것 같은데
![i2](https://github.com/devhotteok/TwitchLink/assets/142792360/f4325fca-989a-47e1-9397-44385b3a2d12)

언젠가 부터 갑자기 안보였던것 같아요.
윈도우 설정이 바뀐건지 아니면 트위치 링크가 바뀐건지
아니면 그냥 제 착각인지는 모르겠지만...

다운로드 상태일때 작업표시줄에서도 표시가 되면 좋겠어요.
다운로드 바 움직이는것 같은 애니메이션이나
아니면 OBS처럼 빨간색 녹화표시가 뜨면 보기 좋을것 같아요.
![i1](https://github.com/devhotteok/TwitchLink/assets/142792360/791ef5df-beb9-40a5-bd44-af3f1d8de057)

덕분에 잘 쓰고 있습니다.
감사합니다.

**Comment by kchwan1218** [comment]
2개 이상 다운받으면 표시 안되더라구요..

**Comment by devhotteok** [comment]
It's a feature that the Qt framework, used to build TwitchLink, no longer supports.
It was dropped when the Qt framework was updated from version 5 to 6.
