### ISSUE TITLE
로그인 오류 - 현재 지원하지 않는 브라우저

### ISSUE THREAD

**Issue by resless55014** [devhotteok/TwitchLink#158]
![image](https://github.com/devhotteok/TwitchLink/assets/145755461/4feed98c-f8ed-4c26-8ed7-d03a9ed5f52c)
로그아웃 후 로그인을 하려는데 이렇게 뜹니다.
Microsoft Edge, Chrome, Twitchlink 모두 최신 버전입니다.

**Comment by resless55014** [comment]
해결방법을 찾았습니다. 
프로그램을 제거하고 2.4.0 버전을 설치, 로그인 후 다시 최신 버전으로 재설치하면 로그인이 유지된 채로 이용할 수 있습니다.

**Comment by devhotteok** [comment]
Closed with commit f81756b7aa2c4ed846e08eef3506bd7dfbf31e55
