### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by alqp1029** [devhotteok/TwitchLink#16]
다시보기 다운로드 시 인코딩 과정에서 다운로드 오류 창이 뜨면서 다운로드 중지가 되서 인코딩이 중간에 끊겨 다운한 영상도 중간에 끊겨있는 현상이 계속 해서 발생합니다

**Comment by devhotteok** [comment]
To investigate the problem, please provide as much information about the problem.
(video ID, download settings, whether the video was downloaded while streaming or not, cropped range if you cropped the video, resulted file duration)

**Comment by alqp1029** [comment]
다운로드 설정은 전부 기본 상태이고 영상은 자르지 않고 처음부터 끝까지 다운로드 받았으며 nanajam777 채널의 지난 다시보기를 다운로드 받았을때 인코딩 오류가 발생하여 영상이 끝까지 저장이 되지 않았습니다

**Comment by alqp1029** [comment]
다운로드 설정은 전부 기본 상태이고 영상은 자르지 않고 처음부터 끝까지 다운로드 받았으며 nanajam777 채널의 지난 다시보기를 다운로드 받았을때 다운로드 오류 메시지가 뜨면서 인코딩 도중 영상이 끊겨 영상이 끝까지 저장이 되지 않았습니다

**Comment by devhotteok** [comment]
To investigate the problem, please provide your video ID.

**Comment by RyuChaeYeon** [comment]
음소거 해제 활성화, 업데이트 추적, 다운로드 속도 10 인 상태로 https://www.twitch.tv/videos/1428241303 해당 영상 전채를 다운로드 받았지만 음소거 부분이 해제되지 않았습니다.

**Comment by devhotteok** [comment]
Closed due to inactivity.
