### ISSUE TITLE
트위치링크 로그인 오류

### ISSUE THREAD

**Issue by picniclv** [devhotteok/TwitchLink#160]
![image](https://github.com/devhotteok/TwitchLink/assets/145886570/33672223-65c4-444d-a685-30c0201be28d)

현재 지원되지 않는 브라우저라고 로그인이 되지 않습니다

![image](https://github.com/devhotteok/TwitchLink/assets/145886570/cd215f13-1320-41c2-9200-b7afb85e510c)

항상 감사히 쓰고 있습니다
살려주세요 ㅠ

**Comment by devhotteok** [comment]
Duplicate of #158
