### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#161]
Sometimes donwloads will cancel repeatedly forcing a lot of retries. One such case:
[TwitchLink_Download_2023.09.25_06-54-14#32963371-0de8-4485-afb0-7105a4bcf0f6.log](https://github.com/devhotteok/TwitchLink/files/12712290/TwitchLink_Download_2023.09.25_06-54-14.32963371-0de8-4485-afb0-7105a4bcf0f6.log)

**Comment by devhotteok** [comment]
This issue is likely related to a problem with your network or the video itself.
If you consistently encounter the same problem with other videos, please provide us with a detailed description of the situation when you reach out again.
