### ISSUE TITLE
Option to reset a download with missing segments

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#162]
Its annoying to have to find it on history or find the video again whenever it happens.
Edit: Sincerely don't know if its useful for people who download streams as they are happening, but it is very annoying for downloading VODs.

**Comment by devhotteok** [comment]
If there are missing segments in the video, it automatically retries several times internally. If the download still fails, it will be marked as missing. This issue may stem from network problems or an issue with the video itself.

**Comment by nameless01234567** [comment]
I understand its just annoying to have to go to the download history to download the same stream again because of missing segments.
