### ISSUE TITLE
Download start slow and have so many missing link 

### ISSUE THREAD

**Issue by dawnte** [devhotteok/TwitchLink#163]
Download start slow and have so many missing link 
[TwitchLink_Download_2023.09.29_11-04-53#fc3e4253-ed1c-423c-ba65-8bd095a43e68.log](https://github.com/devhotteok/TwitchLink/files/12768348/TwitchLink_Download_2023.09.29_11-04-53.fc3e4253-ed1c-423c-ba65-8bd095a43e68.log)

**Comment by devhotteok** [comment]
This issue is likely related to a problem with your network or the video itself.
If you consistently encounter the same problem with other videos, please provide us with a detailed description of the situation when you reach out again.
