### ISSUE TITLE
Doesn't work on windows 11

### ISSUE THREAD

**Issue by maxime-fleury** [devhotteok/TwitchLink#168]
On start up lastest version 3.1.3, it load for a few minutes "checking for updates" and after I see that: 
![image](https://github.com/devhotteok/TwitchLink/assets/81691077/7170dc94-19c7-4f97-8463-256a7d84bcaa)
There nothing wrong with my internet connexion and nothing is else is not woring., I have no idea why it does this, I use google DNS if that helps ??

**Comment by devhotteok** [comment]
It seems to be a temporary network issue.
If you encounter this problem, please wait a few minutes before you try again.
