### ISSUE TITLE
Twitch subscription information cannot be confirmed.

### ISSUE THREAD

**Issue by booksky91** [devhotteok/TwitchLink#169]
![image](https://github.com/devhotteok/TwitchLink/assets/14170836/85327133-bbfb-4d64-9968-860399b513b3)
![cats](https://github.com/devhotteok/TwitchLink/assets/14170836/ee7a5949-058c-4a71-a874-b1dccbd632d4)

I didn't have this issue until yesterday, but today I'm suddenly getting a warning message saying that subscription information cannot be confirmed, even though I am trying to download streams from subscribed channels.

Despite trying personal solutions such as reinstalling, re-logging in, clearing AppData, and resetting the registry, the same issue persists. I tried various versions starting from 2.4.0 just in case, but the issue still persists and remains unresolved.

I tried to find the log information to share it with you, but I couldn't find any logs in the AppData or Program Files

**Comment by ccrowles** [comment]
Same issue

**Comment by devhotteok** [comment]
This is a compatibility issue due to internal changes on Twitch's servers.
It has been identified that the response data being returned by the server has changed.
If the error continues, I will take further action where possible.

**Comment by RVOtakuMike** [comment]
Just letting you know this still happens.

**Comment by edgar1016** [comment]
Thought I'd chime in it still happens.

**Comment by devhotteok** [comment]
Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b
