### ISSUE TITLE
Downloading Sub only videos without sub

### ISSUE THREAD

**Issue by xalyy** [devhotteok/TwitchLink#17]
Hey, can you add downloading Sub only videos without subbing?
This other program already does it, it can download Sub-only VODS without account or sub but its abandoned since a long time and it doesnt have a nice UI like yours. So I guess you could take a look at the code how he did it maybe?
Thanks.

https://github.com/TwitchRecover/TwitchRecover

**Comment by devhotteok** [comment]
TwitchLink respect the rights of streamers. Therefore, there are no plans to add this feature.
