### ISSUE TITLE
Twitch Subscription Recognition Error

### ISSUE THREAD

**Issue by dodoakkak** [devhotteok/TwitchLink#170]
터보 계정인데 어제까지는 멀쩡했는데 광고가 송출될수 있다 구독이 안된 채널이다. 라고 다운 받을때 알림이 뜹니다. 그래도 로그인 상태에서는 광고 페이지가 섞이지는 않는것 같습니다. 로그아웃해보니 광고 뜨고요. 로그 첨부도 해봅니다
[트위치 로그인.txt](https://github.com/devhotteok/TwitchLink/files/13038555/default.txt)

[트위치 로그아웃.txt](https://github.com/devhotteok/TwitchLink/files/13038558/default.txt)

**Comment by devhotteok** [comment]
Duplicate of #169
