### ISSUE TITLE
Twitch Subscription Recognition Error

### ISSUE THREAD

**Issue by barberdd** [devhotteok/TwitchLink#171]
![qq](https://github.com/devhotteok/TwitchLink/assets/142820052/93e5dd05-04e7-4ce4-acc9-1b47e4a58d95)

어제까지는 이상이 없었는데

오늘 갑자기 광고경고알림이 뜨네요

혹시나해서 터보계정 로그아웃했다가 로그인 다시해봤는데도 똑같은 상황입니다

광고가 실제로 들어가지는 않고있는것같지만 신경쓰이네요

**Comment by sample7687** [comment]
저도 같은 증상이네요. 터보이용중인데 같은 경고가뜨는군요. 저도 어제까지는 이상이없었습니다

**Comment by devhotteok** [comment]
Duplicate of #169
