### ISSUE TITLE
Questions about Banned Channels

### ISSUE THREAD

**Issue by rjseka143** [devhotteok/TwitchLink#172]
안녕하세요, 도저히 어디에 물어봐야할지 고민하다가 여기에 적게 되는점 일단 사과드리겠습니다....
아무리 답을 찾아보려고 해도 안되는 상황이라 답답한 마음에 여기에 적어봅니다....
다름이 아니라 twitchlink는 한번 밴 당한 채널은 녹화를 못하는건가요? 현재 밴 당한 채널이 있는데
unauthorized라고 뜨면서 녹화가 중단됩니다.........물론 그냥 로그 아웃하거나 그래도 되지만 그때는 광고 이슈도 있고 해서........

다른 질문은 밴 당한 채널에서는 스트리머가 설정을 바꿨는지 시청조차 못하게 됐습니다...다만
구글에 다행히 twitch-Aniban이라는 extension이 있어서 채팅은 볼수있게 됐는데 여전히 영상은 아직 시청 불가능입니다
혹시 우회하거나 저런 extension처럼 다운 받아서 보는 방법이 있을까요? 부디 방법을 알려주세요.............부탁드립니다

Hello, I couldn't figure out where to ask, so I'd like to apologize for writing it here...
No matter how hard I try to find the answer, I can't, so I'm writing this here out of frustration...
The other thing is, isn't twitchlink unable to record a channel that has been banned? There is a channel that is currently banned.
The recording stops with the message "unauthorized"... Of course, you can just log out, but then there are advertising issues...

Another question is that you can't even watch the banned channel because the streamer changed the settings...but
Luckily, Google has an extension called twitch-Aniban, so I can watch the people's chat, but I still can't watch the video.
Is there a way to bypass it or download it like an extension like that? Please tell me how to do it.............please

이 글이 문제시 삭제처리 하겠습니다....(꾸벅)

**Comment by devhotteok** [comment]
I'm sorry, but I can't help you with that. Also, this request is not related to the scope of this project.
