### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by ElementShadow** [devhotteok/TwitchLink#177]
sometimes file downloaded with wrong fps, sometimes it right 60 fps, other time its 59.940 fps which break editing timeline in resolve and make audio desync overtime. Its very annoying

VOD 100% 60 fps and not 59.940 in obs 

https://www.twitch.tv/videos/1962448316 - vod

I did download same vod with Twitch Downloader and vod have 60  fps.
With Twitch Link for some reason its 59.940 which ruin editing
Again i did download with Twitch Link and its again wrong FPS

**Comment by ElementShadow** [comment]
apparently no one care, F

**Comment by devhotteok** [comment]
The behavior you're experiencing may vary depending on the characteristics of the video.
If you've changed the download format to something like mp4, the issue could arise during the process of converting the video into the appropriate format.
