### ISSUE TITLE
Missing Segments

### ISSUE THREAD

**Issue by ywj515** [devhotteok/TwitchLink#18]
임시폴더를 확인해보니, ts파일이 일부 누락되어 영상과 음성의 싱크가 맞지 않는 현상이 종종 생기네요.
ts파일을 검사하는 과정을 추가하여 누락이 없도록 만들어주시면 좋을 것 같습니다.

**Comment by devhotteok** [comment]
It is an issue where some data is missing due to server or network issues. Currently, TwitchLink will request this data a few more times and give up if the error persists.

**Comment by devhotteok** [comment]
This feature has already been added internally and will be released soon.
