### ISSUE TITLE
Intermittent Program Reset

### ISSUE THREAD

**Issue by nononyami** [devhotteok/TwitchLink#181]
간헐적으로 트위치링크가 처음 다운받았을때처럼 설정이 아예 날아가버립니다.

오늘로 3~4번째 된 것 같은데 왜 설정이 날아가는지 잘 모르겠습니다.

**Comment by devhotteok** [comment]
The issue you're experiencing can occur if the files containing the program's data are deleted.
Additionally, software designed to clean up disk space or antivirus programs could also cause this to happen.
Please check if any such applications on your system might be affecting the program's data files.
