### ISSUE TITLE
TwitchLink reinstalling itself

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#183]
Twice TwitchLink opened as if I hadn't installed it, resulting on all my configurations being gone.

**Comment by devhotteok** [comment]
It seems like you are running the installer instead of the program itself.
Please make sure to run the program that was installed through the installer.

**Comment by rOoHzzz** [comment]
I's running into the same problem with the desktop shortcut. It popped up a window with a big "lunch" button and everything's gone like a newly installed after that.
