### ISSUE TITLE
Batch download

### ISSUE THREAD

**Issue by sizzl3** [devhotteok/TwitchLink#186]
클립을 하나하나 저장은 가능한데 일자 별로 구분해서 일괄 다운로드를 할 수 있는 툴이 제대로 없더라고요.
트위치 링크처럼 태그 설정이 자유롭지도 않고.

특정일자~ 특정일자까지
클립의 일괄 다운로드 기능이 추가 됐으면 좋겠습니다.

**Comment by devhotteok** [comment]
Duplicate of #38
