### ISSUE TITLE
Error of opening the souce code script(ModuleNotFoundError: No module named 'Services.Twitch.GQL')

### ISSUE THREAD

**Issue by karstenlee10** [devhotteok/TwitchLink#188]
C:\Users\xxxx\Desktop\TwitchLink-3.1.3\Core\Qt\QtWebEngineWidgets\QWebEngineProfile.py:14: SyntaxWarning: invalid escape sequence '\S'
  formatString = re.sub("QtWebEngine/\S*", "{appInfo}", self.httpUserAgent()) if Config.USER_AGENT_FORMAT == None else Config.USER_AGENT_FORMAT
C:\Users\xxxx\Desktop\TwitchLink-3.1.3\Services\Image\UrlFormatter.py:8: SyntaxWarning: invalid escape sequence '\d'
  IMAGE_SIZE_FILTER = re.compile("-\d+x\d+")
[root] [INFO]

TwitchLink 3.1.3

ⓒ 2024 DevHotteok.

[root] [INFO] Windows 11 10.0.22631; AMD64;
[root] [INFO] Application started successfully.
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\TwitchLink-3.1.3\TwitchLink.py", line 1, in <module>
    from Core.Ui import *
  File "C:\Users\xxxx\Desktop\TwitchLink-3.1.3\Core\Ui.py", line 1, in <module>
    from Core import App
  File "C:\Users\xxxx\Desktop\TwitchLink-3.1.3\Core\App.py", line 39, in <module>
    from Services.Twitch.GQL.TwitchGQLAPI import TwitchGQL as _TwitchGQL
**ModuleNotFoundError: No module named 'Services.Twitch.GQL'**<----

**Comment by karstenlee10** [comment]
@devhotteok

**Comment by devhotteok** [comment]
It seems that the program has not been installed properly. Some antivirus programs can cause such results. Please try reinstalling it.
