### ISSUE TITLE
Has TwitchLink been abandoned?

### ISSUE THREAD

**Issue by MartynHollandNL** [devhotteok/TwitchLink#192]
Hi folks, 

Anyone know if TwitchLink is still under development? Cant see any recent activity from the developer.

**Comment by Stav06** [comment]
Hopefully not. It by far my fav software to manage downloading/recording VODs and with a little tweaking could be perfect.

**Comment by devhotteok** [comment]
I apologize for any delays in response.
Due to my busy life, it's challenging to respond promptly, but rest assured, this project has not been abandoned.
