### ISSUE TITLE
TwitchLink for Other Platforms

### ISSUE THREAD

**Issue by 114call** [devhotteok/TwitchLink#194]
이제 트위치는 한국서비스 종료라서
대부분의 트위치 스트리머, 시청자들도 치지직으로 이동한 상태인데
트위치링크랑 비슷한 치지직링크도 만들어주시면 좋을것같아요.
https://chzzk.naver.com 

그동안 트위치링크 잘 사용했습니다.
고맙습니다.

**Comment by devhotteok** [comment]
I'm sorry, but TwitchLink is a project specifically for Twitch.
Currently, there are no plans to start a project for other platforms.
