### ISSUE TITLE
Subscriber-Only Video Download for non-subscribers

### ISSUE THREAD

**Issue by ArtemkaJS** [devhotteok/TwitchLink#197]
There is a possibility to download VODs even if you are not a subscriber. 

Example of this feature: 
https://github.com/TwitchRecover/TwitchRecover

![изображение](https://github.com/devhotteok/TwitchLink/assets/6023512/2aca134b-c9d6-4bd6-8f1a-a22bc6d64e15)

It would be great if this feature was added to TwitchLink.

**Comment by devhotteok** [comment]
Duplicate of #17
