### ISSUE TITLE
클립다운로드시 네트워크 오류가 뜹니다.

### ISSUE THREAD

**Issue by Lwnlcks** [devhotteok/TwitchLink#2]
![gfddf](https://user-images.githubusercontent.com/72176091/121379919-7079eb80-c97f-11eb-876a-b85c018e1569.PNG)
다시보기는 정상적으로 작동하지만 클립을 다운로드 할 경우 위 사진처럼 오류가 뜹니다

**Comment by devhotteok** [comment]
Closed with commit 19872dbac5a9b425a938d97a1de2a964a22e40ca
