### ISSUE TITLE
Unable to load browser

### ISSUE THREAD

**Issue by Naiosama** [devhotteok/TwitchLink#20]
Hi,

I have this error although I have Chrome and Edge

![Twitchlink error](https://user-images.githubusercontent.com/64286488/161983878-be4442dc-6fda-469c-af5e-f1c64f9d8329.png)

I really need to download sub only video, could someone help me out?

**Comment by devhotteok** [comment]
Try running the program as administrator.
Also, make sure you are using the latest version of your browser.

**Comment by FabioCarta** [comment]
Got the same issue on win10. Tried running as administrator and edge is up-to-date aswell.

**Comment by Buurtjee** [comment]
Same issue, all is up to date and I get the same error. Have a Chromium browser (Brave) and Edge, having both open still gives this error.

**Comment by devhotteok** [comment]
Closed with commit 936c8cf238b435206e4b7be73cf52018aff84e75
