### ISSUE TITLE
Suggestion - Ability to watch SUB ONLY twitch streams

### ISSUE THREAD

**Issue by gzachariadis** [devhotteok/TwitchLink#200]
I am not aware of any way to accomplish this as of now, I am opening this issue to discuss.

Not aware if inside the scope of this extension, so feel free to close if that's the case. 

Investigating this I little bit using the networking tool, I can see that video-edge xhr request still go through to my browser even though I am unable to watch without subbing.

**Comment by devhotteok** [comment]
Duplicate of #17
