### ISSUE TITLE
ERROR Download Aborted (Network ERROR)

### ISSUE THREAD

**Issue by tagirch1k** [devhotteok/TwitchLink#207]
greetings, when downloading a live broadcast via a router or cable, the error Download aborted (Network error) is issued, I tried to distribute the Internet via the phone and everything worked out, but nothing is downloaded specifically through the cable Internet, perhaps a ban on IP, help me sort out this problem and solve it

**Comment by devhotteok** [comment]
It is most likely to occur if there is an issue with the user's network configuration or if the network speed is too slow. Please check your network settings and consider lowering the download speed in the settings to avoid overloading the network.
