### ISSUE TITLE
Unmuting function is not working

### ISSUE THREAD

**Issue by TBloop** [devhotteok/TwitchLink#21]
I just downloaded TwitchLink and one of the reasons was because it said it can unmute VODs. I tried downloading a VOD with muted parts, and made sure the "unmute" checkbox was checked, but the resulting .ts file is still muted.

Is there something I can do to fix this?

The VOD I downloaded is: https://www.twitch.tv/videos/1457933986

Much appreciated!

**Comment by devhotteok** [comment]
Duplicate of #3
