### ISSUE TITLE
download is aborted (system error)

### ISSUE THREAD

**Issue by Larvsas4450** [devhotteok/TwitchLink#212]
Why is it no longer possible to watch the videos if the download fails due to a system error? So you download a dead video with a lot of GB without being able to watch it. Because of insufficient disk space. If there is an internet error, you can still see the whole video. But not if the download is aborted (system error).

**Comment by Larvsas4450** [comment]
and why is there no repair software to fix the playback error 0xc00d36c4 ?

**Comment by devhotteok** [comment]
As mentioned in the description of the download options, if you set the file extension to ".ts", you will be able to watch the video without issues, even if a problem occurs during the download process.
