### ISSUE TITLE
Can we save the app setup ?

### ISSUE THREAD

**Issue by satrincha** [devhotteok/TwitchLink#213]
Hi, i got a windows BSOD, i was recording an audio with TwitchLink. When i lauch the app after having restart my computer, it got a reset with all my setup ... i had to login again, setup the app and add all the channels in the Scheduled Downloads tab....

Is there a way to save the app setup ?? manually or not !

**Comment by devhotteok** [comment]
The app settings are automatically saved when the app is closed. If the app is forcibly terminated or crashes, there is a high chance that the settings file could become corrupted, so the app does not attempt to save the settings in such cases. To ensure your settings are safely saved, please restart the app after making the necessary changes.
