### ISSUE TITLE
Add retry when network error on starting

### ISSUE THREAD

**Issue by Mishasama** [devhotteok/TwitchLink#214]
When the program starts up and encounters a network error it is not possible to continue using the program and must be closed and restarted.

This is very cumbersome and causes unnecessary waste of computing resources. A retry button should be provided on error for quick re-initialization.

Besides, it's strange that a downloader has to have an active network connection at startup. Why can't I just start the downloader and then connect to the network?

**Comment by devhotteok** [comment]
I will consider adding a retry button. The reason a network connection is required at the start is to dynamically retrieve and apply settings or URLs that may change over time, allowing the app to adapt to various updates without needing to update the app itself.

**Comment by Mishasama** [comment]
> The reason a network connection is required at the start is to dynamically retrieve and apply settings or URLs that may change over time, allowing the app to adapt to various updates without needing to update the app itself.

NO. It should only needed when any scheduled download is activated. Or poll for rule updates in the background after the program starts, instead of preventing the program from continuing in the first place.
In fact, the rules aren't updated every day and usually don't affect downloads even if you can't check for updates.
