### ISSUE TITLE
I can't download video or clip...

### ISSUE THREAD

**Issue by Mystiker5579** [devhotteok/TwitchLink#22]
I would like to raise two issues.

First, every time you enter a Twitch link, you will be asked to agree. It's a little uncomfortable to press again.

Second, even if I search for a streamer I want or search for a URL, the Twitch link suddenly turns off.
If it's just me, I think my computer is the problem, but if other people are like me, I think there's a problem.
(The streamer ID is 'lumyon3'. And this was the case even before the big update. But just a month ago, it worked just fine.)

I'm Korean, so I'm not good at English. Please forgive me for using a translator.

**Comment by devhotteok** [comment]
1. The 'Do not show this again' function will be added later.
2. Uninstall the program and delete the 'TwitchLink' folder in the location where the program was installed(mostly C:\Program Files (x86)). Then try reinstalling. Please let me know if this solves it or not.

**Comment by devhotteok** [comment]
If possible, could you please do the following?
1. Open File Explorer.
2. Enter '%temp%\TwitchLink' in the address bar.
3. Attach the files inside.

**Comment by niri286** [comment]
Sorry to cut in this issue.
I got almost the same problem what TwitchLink will freeze and shut down without any operation.
Here I put up the files you refered. Maybe it can be helpful for you. 
[TwitchLink_2386000473536.txt](https://github.com/devhotteok/TwitchLink/files/8668959/TwitchLink_2386000473536.txt)

**Comment by Mystiker5579** [comment]
Oh, I guess it was because I downloaded Twitch Link to the SSD.
Originally, it didn't work even when it was in C.
but i downloaded Massive Update to D, maybe it is a reason.

i solve it, thank you for writting comment
