### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by charlotte1210** [devhotteok/TwitchLink#225]
i can't log in
<img width="364" alt="螢幕擷取畫面 2024-11-16 075658" src="https://github.com/user-attachments/assets/ee7e2fa2-6225-4c22-97a6-72d6d36e8808">

**Comment by Kevinnmn** [comment]
i cant log in either 
![Screenshot 2024-11-17 145629](https://github.com/user-attachments/assets/1ff5a7ce-384f-4ab0-9b73-93cbf65a3877)

**Comment by devhotteok** [comment]
A fix for this issue has been applied to the server. However, if you encounter the same problem again, please feel free to open a new issue. :)
