### ISSUE TITLE
i can't login

### ISSUE THREAD

**Issue by charlotte1210** [devhotteok/TwitchLink#227]
why i can't login again?
<img width="353" alt="螢幕擷取畫面 2024-11-28 054840" src="https://github.com/user-attachments/assets/088e643b-09ea-46a9-8727-d0b026c39b1d">

**Comment by Kevinnmn** [comment]
hi i cant log in again

**Comment by Kevinnmn** [comment]
> It seems that Twitch has changed its fingerprinting method for detecting browsers. This issue appears to be related to a compatibility problem with the Chromium browser inside PyQt WebEngine. Since I am currently using PyQt's WebEngine, directly addressing this may not be feasible. I will explore alternative solutions. If anyone has a good workaround or solution, please share it in the comments below. Thank you!

is it possible to connect chrome to it? we need it badly

**Comment by VyzerMusic** [comment]
What about having a "login" window open in the user's default browser? then have the user login using their browser?

**Comment by devhotteok** [comment]
Closed with commit a2fa763c95ab7a5bf2698feaa11323eb66ab3a51
