### ISSUE TITLE
How to Back Up/Restore Settings

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#228]
I had a Twitchlink crash today and ALL my settings with over 40 scheduled downloads deleted.(Only settings, not the actual files) (Also, I cannot login again after the crash) 
There really should be a setting backup feature in this program, I do not even know where the settings usually are saved.
I tried a Windows restore point but sadly the settings are still lost.

**Comment by devhotteok** [comment]
You can find the `settings.json` file in the `%appdata%\TwitchLink` directory, which contains all the settings for TwitchLink.
If you want to back up your settings, simply copy this file to another location.
To restore the settings, replace the existing file with your backup whenever needed.
