### ISSUE TITLE
Just help me - twitchlink install is not working

### ISSUE THREAD

**Issue by jaemmin** [devhotteok/TwitchLink#26]
I downloaded twithlinksetup.exe, and I tried to install it. But, It doesn't work! In task manager, setup/uninstall process is working, but it doesn't use CPU. maybe, my computer has problem. How can I solve it
//////
설치 파일을 다운받아서 실행하였지만, 설치창이 표시되지 않습니다. 작업관리자에는 setup/install 이 작동되고 있는 걸을 확인했지만, CPU 점유율이 0%인 것을 보니 올바르게 작동하지는 않은 것 같습니다. 어떻게 해결 할 수 있을까요?

**Comment by devhotteok** [comment]
Try running the installer as administrator.
Also, make sure you are using Windows 10 or higher.

**Comment by devhotteok** [comment]
Closed due to inactivity.
