### ISSUE TITLE
Automatic Download Feature

### ISSUE THREAD

**Issue by TBloop** [devhotteok/TwitchLink#28]
I apologize if this is a duplicate, another person submitted a feature request that sounds similar but I did not fully understand what they were asking for. 

I would be wonderful if I could start the application to automatically start download when a streamer goes live. Sometimes I will be away from my PC and the VOD will get deleted, so I miss the stream. If I could set it to detect when they go live, and then automatically record, that would be awesome.

Thanks for the software, it works great!

**Comment by devhotteok** [comment]
Closed with commit 0bc563ca7d98d42e2dc819c83a13dcf956ca27c0
