### ISSUE TITLE
Installation issue in windows 7

### ISSUE THREAD

**Issue by jaideep-sp** [devhotteok/TwitchLink#29]
After installing the program it is showing this pop-ups-
![error1](https://user-images.githubusercontent.com/81135835/186215092-13a78dd5-0c8b-4fb6-b227-1c8701e76f98.PNG)
![error2](https://user-images.githubusercontent.com/81135835/186215113-f911edca-fd20-44c8-bc1d-fc1f758708c2.PNG)

i've downloaded the 'python39.ddl' from internet paste it in /system32 as well as replace it in /TwitchLink. but same popup is coming.

**Comment by devhotteok** [comment]
Sorry, TwitchLink only supports Windows 10 or higher.
