### ISSUE TITLE
Default resolution on download

### ISSUE THREAD

**Issue by nStoyanov07** [devhotteok/TwitchLink#31]
When i start to download a video the default resolution is 720p can you try to make an option from the settings to choose what reso i what and save that option, becouse is so annoying to choose 1080p everytime i want to download. It will be 10 times better if i can save my default reso. Thanks :)

**Comment by tkelman** [comment]
It seems like defaulting to 720p is new behavior as of 2.2.1, but I'm not seeing anything clear in the commit that would have caused that change.

**Comment by devhotteok** [comment]
It is ambiguous to set a default value because each video has a different list of resolutions.
Instead, I changed the sorting method.

**Comment by devhotteok** [comment]
Closed with commit 3d51bdfdfb9885a90c93dbdfd3b8f618fc5fccb5
