### ISSUE TITLE
Unable to run the TwitchLink

### ISSUE THREAD

**Issue by wlucyy** [devhotteok/TwitchLink#32]
![问题](https://user-images.githubusercontent.com/54660922/194921644-da681a28-feea-48f2-8a9a-f5b1e136fc1d.png)
Everytime I run the TwitchLink, it will show me this info.
My computer is Windows 10.
TwitchLink 2.2.1.
Besides, I use VPN. I had changed the proxy for many times but it didn't work.

**Comment by timiasuu** [comment]
me too

**Comment by devhotteok** [comment]
Most of them are literally temporary problems.
Try again later.
