### ISSUE TITLE
Video framerate bug in new version

### ISSUE THREAD

**Issue by Nutyax** [devhotteok/TwitchLink#34]
Hello, I installed the new version today and I noticed that my broadcast is progressing very fast. As a result of my reviews, I realized that the video frame rate is 1000 FPS instead of 60.00 FPS.

![bug](https://user-images.githubusercontent.com/117934573/201159589-5b60ac43-7c4a-4145-a119-5428c97db7f9.png)

**Comment by devhotteok** [comment]
Please attach the log file.

**Comment by devhotteok** [comment]
Closed due to inactivity.
