### ISSUE TITLE
TwitchLink OpenGL 2.0 issue (트위치링크 OpenGL 2.0 관련 문제)

### ISSUE THREAD

**Issue by CatsAreFluid** [devhotteok/TwitchLink#35]
![image](https://user-images.githubusercontent.com/118010707/201394962-426f8b42-cbf2-4625-aa9c-f77507df0c59.png)

TwitchLink is prompting error message to install a graphics driver that supports OpenGL 2.0 or higher. I currently have a GeForce driver installed that supports OpenGL 3.0 and highers. I had installed the ANGLE OpenGL ES 2.0 Emulation Library in the location of TwitchLink.exe, but the issue is not resolved.

TwitchLink에서 OpenGL 2.0 이상의 버전을 지원하는 그래픽드라이버 설치를 요구하는 issue가 발생합니다. 현재 OpenGL 3.0 이상의 버전을 지원하는 GeForce 드라이버가 설치되어 있습니다. ANGLE OpenGL ES 2.0 에뮬레이션 라이브러리를 TwitchLink.exe의 위치에 설치해 보았으나 문제가 해결되지 않습니다.

**Comment by devhotteok** [comment]
There seems to be a problem with your PC environment, and there seems to be nothing I can do to help. Try installing it on another computer.
