### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by Mystiker5579** [devhotteok/TwitchLink#36]
I am a regular user of Twitchlink.

However, whenever my computer downloads a file, it is automatically downloaded to the D drive.
I still have to move it to the C local by myself.

Can you tell me how I can change the save path so that I can download the file to my C local disk?
I sometimes get trouble every time they update.

![트위치 링크1](https://user-images.githubusercontent.com/105278265/202352001-dd0f3b74-0ca5-46de-b702-fbdb50b7661f.PNG)

**Comment by devhotteok** [comment]
The default path is set to your system drive. Changing the installation path is not supported yet.
