### ISSUE TITLE
Enhancement Request:  Save to incremented filename.

### ISSUE THREAD

**Issue by sqlurp** [devhotteok/TwitchLink#39]
When a filename already exists after clicking the quick download button, the options are to either overwrite the file or do nothing.  Would it be possible to add an additional option to increment the filename in this selection window? (Ex. filename(1).mp4, filename(2).mp4)  We often have to stop / start recordings to avoid losing the entire recording due to live download errors.

![2022-12-12 15_08_33-Window](https://user-images.githubusercontent.com/120421547/207155226-39c04163-4e1c-44b6-b7aa-f623af57a12e.png)

**Comment by devhotteok** [comment]
Closed with commit 21a74a669a946f8223e2ce83c5dfe5c40c5ae5ba
