### ISSUE TITLE
인터페이스의 글자 크기 문제.

### ISSUE THREAD

**Issue by sample7687** [devhotteok/TwitchLink#4]
현재 4k모니터(4096x2160)를 사용중이고 윈도우에서 배율을 175%로 사용중입니다
아래 그림에 보이듯이 인터페이스의 글자가 위아래가 잘리고
그 크기때문인지 검색 입력창들이 밀려서 검색을 할수가없습니다.
옵션창도 그렇고 모든창들이 이런상태인데.
인터페이스의 글자 크기를 조절하거나  윈도우 배율과 상관없이 100%로 출력가능하게 수정이가능한가요?
![트위치링크](https://user-images.githubusercontent.com/85941705/122054298-81fd4080-ce22-11eb-910b-1d2be43c2b74.jpg)

**Comment by devhotteok** [comment]
Closed with commit ad3d5780d37cece7f7e9586059ec0000144ca9bb
