### ISSUE TITLE
Live download voice problem

### ISSUE THREAD

**Issue by raymondhung010** [devhotteok/TwitchLink#42]
When I try to download a stream through live stream download, the voice is not same as the stream .

**Comment by raymondhung010** [comment]
It's just like the tone has turn up a little bit.

**Comment by skyfox1977** [comment]
Okay, so I noticed this is only a problem when saving to .MP4. If you save to .TS there seem to be no problem with the pitch. Is this something that can be fixed in future releases?

**Comment by devhotteok** [comment]
Depending on the streamer's network, the file may be corrupted.
Therefore, it is recommended to download in the original 'ts' format.
You can also try using a different video player.
