### ISSUE TITLE
모니터를 끄고 다운로드 받으면 잦은 오류가 발생합니다.

### ISSUE THREAD

**Issue by zksxm** [devhotteok/TwitchLink#45]
1. 한방송이 오래 지속되어 오래 저장을 하고 종료시 동영상 파일이 깨짐
2. 방송 시간과 상관없이 생방송이 끝났지만 계속 녹화를 하는것으로 보이며 종료 시킬시 오류남.

**Comment by devhotteok** [comment]
Closed due to inactivity.
