### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by thdtldus** [devhotteok/TwitchLink#47]
Attempt to login to access subscriber only video leads to a secondary chrome application opening; upon entering login info, receive an error stating that the chrome browser opened by the app is not supported; login fails

**Comment by ColtBolt** [comment]
I was able to login today, perhaps try now?

**Comment by thdtldus** [comment]
Unfortunately didn't work for me :(

**Comment by thdtldus** [comment]
<img width="1188" alt="스크린샷 2023-02-14 02 57 16" src="https://user-images.githubusercontent.com/50155301/218715705-347bc550-9db7-431d-9d01-e1a8139906c7.png">

**Comment by thdtldus** [comment]
<img width="215" alt="스크린샷 2023-02-14 02 58 13" src="https://user-images.githubusercontent.com/50155301/218716216-7eac5eae-4c6b-48fb-bac6-b4a73c50b2f4.png">
<img width="449" alt="스크린샷 2023-02-14 02 58 02" src="https://user-images.githubusercontent.com/50155301/218716221-75eb0276-1bb3-4106-878d-b6c7d3824fad.png">

**Comment by devhotteok** [comment]
It seems that you are using a malformed version of TwitchLink.
Be sure to use the latest version released from this repository.
