### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by Leatherback-Azi** [devhotteok/TwitchLink#5]
[Repository](https://github.com/Leatherback-Azi/TwitchLink-MacOS)

1. 맥 버전 트위치링크입니다.
2. 윈도우 1.0.1 버전을 기반으로 수정되었으며,
3. 추후에 새로운 버전으로 계속 업데이트 해줄 계획입니다.
4.Intel, Apple Silicon Mac에서 구동되며,
5. 로그인 기능 사용을 위해서는 Chrome 브라우저가 있어야 합니다.
6. 추가적인 설명이 필요하시다면 상단 repository 의 readme.md를 확인해 주세요.

======English======

1. Mac Version of Twitchlink.
2. Based on Windows TwitchLink 1.0.1.
3. Planning to support continuous update in the future.
4. Running on Intel, Apple Silicon Mac.
5. To use Log In, Must have Chrome browser.
6. If you need additional explanations, please visit "readme.md" in top of Repository URL

**Comment by ysj-2383** [comment]
**안녕하세요 제작자님 제가 현재 제작자께서만드신 [TwitchLink] 맥버전을 사용중입니다. 구동은 되나 토니엔진 상태로 자른 부분만 따로 다운이 안된더라구요 혹시 그 이유와 맥버전은 따로 업데이트를 안해주시는 이유를 알수 있을까요?**

**Comment by GeekFoolish** [comment]
+1 for mac support!

**Comment by Koston411** [comment]
When trying to login I have the message "Your browser is not currently supported."

**Comment by 114call** [comment]
맥 버전도 업데이트 해주세요

**Comment by devhotteok** [comment]
Thank you so much for your patience and continued interest in this project!
I’m excited to share that official macOS support is finally here. 🎉
Feel free to give it a try and let me know if you encounter any issues!

Closed with commit d5bf121291784c5643ade9c653ef822b5ea65b2b
