### ISSUE TITLE
"Preparing stream" In the beginning of video

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#52]
On some live stream downloads I get a couple of seconds where it says "preparing stream" Is it possible to to have the program filter this out automatically?
It seems to happen on some streams but not all. An d it does not matter if I choose .mp4 or .ts as format.

![Snapshot](https://user-images.githubusercontent.com/66199825/216759319-5cac8067-d58f-4f0b-b3dd-bb34e346597f.png)

**Comment by devhotteok** [comment]
This is displayed when Twitch is running ads.
TwitchLink does not filter this.
To remove ads, log in with a subscribed account or an account with another ad removal benefits.
