### ISSUE TITLE
[Enhancement] Minimize to tray

### ISSUE THREAD

**Issue by TBloop** [devhotteok/TwitchLink#53]
Hello,

First, I wanted to thank you for implementing scheduled downloads. This is great! 

I just had a small feature suggestion: 

Now that it has scheduled downloads, it would be nice to minimize it to the system tray since it may be open for many hours, waiting for the stream to start. It would free up space on the start menu. 

Additionally, a small notification to alert you that the download started would be nice. 

Thanks!

**Comment by devhotteok** [comment]
Closed with commit 1b2f4e038d0c3940c1ca79e48fd835521f572195
