### ISSUE TITLE
다운로드 완료 후 종료기능에 관해

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#58]
![image](https://user-images.githubusercontent.com/113231866/217604974-7371aca6-dafa-40de-845a-788dd4c4c851.png)

예약 다운로드 기능 사용중일시

다운로드 완료 후 종료기능이 비활성화가 되는데

이 기능 활성화 옵션을 추가할수는 없을까요?

녹화가 종료되면 자동으로 종료되는기능이 정말 편했었는데

예약 다운로드 기능이 생긴 후 사용을 하지 못하고있네요

**Comment by devhotteok** [comment]
Try disabling Scheduled Downloads.

**Comment by gtskks** [comment]
I know I can disable it, but

I'm wondering if I can use that while using the Scheduled Downloads feature.
