### ISSUE TITLE
{id} Does not work on scheduled streams

### ISSUE THREAD

**Issue by skyfox1977** [devhotteok/TwitchLink#59]
I noticed when the app automatically downloads a stream, It does not automatically get the ID number. I use:
"{channel_name}_{date}_{title}_{id}_{resolution}_{type}" as a filename and {id} becomes "None"
It seem to work if I cancel the download and retry downloading it.
I am using latest 2.3.1

**Comment by devhotteok** [comment]
It's not a bug. The ID value is not applied to the first download because the download starts as soon as the stream starts, before the program loads its stream data.
