### ISSUE TITLE
Retry if interrupted due to network error

### ISSUE THREAD

**Issue by fade-out-0770** [devhotteok/TwitchLink#6]
안녕하세요. 항상 잘 쓰고 있습니다. 감사합니다.

제가 저장되지 않는 생방송 녹화를 자주하는 편인데 간혹 생방송이 되는중인데도 불구하고 완료가 되어버리는 경우가 발생합니다. 인터넷 회선불량으로 발생하는거라 예상이됩니다만, 만약 회선불량의 경우라면 회선이 회복되었을경우 자동으로 녹화를 재개하는기능을 넣어주실수 있을는지요? 

참고할만한사항으로, 자주는 아닙니다만 업데이트 추적을 사용할 경우에도  녹화가 완료되어버리는경우가 발생합니다.(제 생각이지만 추가파일을 확인하는 타이밍과 인터넷 회선이 불량해진 타이밍이 우연하게 일치해서 그런 것이라 생각합니다.)  

항상 행복하시고 좋은 하루되시길 바랍니다.

Translate
---------------------
Hello, I'm always using it well. Thank you.

I often record live broadcasts that are not saved, but sometimes they are completed even though they are being broadcast live. It is expected to occur due to poor Internet lines, but if the line is bad, can you automatically resume recording if the Internet line recovers?

For your information, it's not often, but even if you use update tracking, the recording is sometimes completed. (I think it's because the time when the program checks additional files and the time when the Internet line is bad coincidentally coincided.)

I hope you are always happy and have a good day. - Translated from Papago.

**Comment by devhotteok** [comment]
Closed with commit fb781c56d915871feb3561b2fc4f9a42046327af
