### ISSUE TITLE
ver 2.3.1 adobe premiere pro cc에서 녹화한 화면을 부르면 녹색 화면이 로드 됩니다.

### ISSUE THREAD

**Issue by nam-goangsu** [devhotteok/TwitchLink#64]
2.3.1 버전으로 녹화 한 파일은 window 플레이어에서 는 정상적으로 플레이 됩니다.
 하지만 adobe premiere에서 편집 하고자 하는 경우 화면이 여러개가 나타나며, 하단에는 녹색 화면이 표현됩니다.

2.3.0 버전의 경우 정상적으로 표현 됩니다.
2.3.0-> 2.3.1 업데이트 이우 이럽니다.

**Comment by devhotteok** [comment]
There are no related changes in that update.
Your file may be corrupted.
Or maybe it's a problem with your video player.
