### ISSUE TITLE
Twip VOD & CLIP Support

### ISSUE THREAD

**Issue by 4BMtolobPL** [devhotteok/TwitchLink#65]
https://vod.twip.kr/

Hello, I'm always using it well. Thank you for developing a useful program.

Since the end of last year, Twip has started to support vod and clip replay for some streamers.
It will be able to download high-definition replay and clips without any other programs (such as vpn), so it would be great for Korean viewers if TwitchLink supports Twip.

-------------------------------------

안녕하세요. 프로그램 잘 사용하고 있습니다. 좋은 프로그램 개발 감사합니다.

작년말쯤부터 트윕에서 일부 스트리머들의 vod와 클립 다시보기를 지원하기 시작했습니다.
(VPN같은) 다른 프로그램 없이도 고화질 다시보기와 클립을 다운로드 할 수 있을거라 생각하기 때문에 TwitchLink에서 트윕을 지원한다면 한국 트수들에게 정말 좋을것 같습니다!

**Comment by devhotteok** [comment]
TwitchLink does not and will not support other platforms.
