### ISSUE TITLE
Duplicate empty files created occasionally with real files

### ISSUE THREAD

**Issue by nam-goangsu** [devhotteok/TwitchLink#67]
예약 다운 설정 후. 
1회차 예약 다운은 파일 1개 생성
2회차 예약 다운 되면 파일 2개 생성됨 [ (정상 녹화) 파일명 정상용량(gb) / (정상 녹화 파일명) (0) 5mb 크기 ]
3회차 예약 다운 되면 파일 3개 생성됨 [ (정상 녹화) 파일명 정상용량(gb)/ (정상 녹화 파일명) (0) 5mb 크기 / (정상 녹화 파일명) (1)5mb 크기]
....

n회차 예약 다운 되면 파일 n개 생성됨 

사용버전 2.3.2
window 10

**Comment by devhotteok** [comment]
Closed with commit 1b2f4e038d0c3940c1ca79e48fd835521f572195
