### ISSUE TITLE
로그인이 되지 않습니다

### ISSUE THREAD

**Issue by kotoha5479** [devhotteok/TwitchLink#7]
크롬과 엣지 모두 설치되있는데 로그인이 불가능합니다.
![image](https://user-images.githubusercontent.com/92331749/136836844-b16253f2-6481-4227-8fae-5b2327694994.png)

**Comment by starft8900** [comment]
1.1.0 버전 설치 후 동일한 증상이있었는데 크롬설치 후 프로그램 관리자 권한으로 실행하니까 크롬으로 로그인이되네요

**Comment by devhotteok** [comment]
Closed due to inactivity.
