### ISSUE TITLE
How to search VODs by date?

### ISSUE THREAD

**Issue by ShmulikKraus** [devhotteok/TwitchLink#76]
How to search VODs by date?

Hello, I was looking for a replacement for the now defunct Twitch Leecher and came across TwitchLink.

It looks very capable and works well but it is crucial for me to be able to search a channel for past broadcasts within a date range (Twitch Leecher had this option), because I'm downloading from a channel with thousands of videos and getting to videos from 2019 is almost impossible by scrolling through all the channel's videos.

Is there a way to search a channel for past broadcasts within a date range in TwitchLink?

Also, not as important, but is there a way to change the temporary files folder to something other than the download location?

**Comment by devhotteok** [comment]
Currently, we don't offer that feature.
