### ISSUE TITLE
무한로딩현상

### ISSUE THREAD

**Issue by sample7687** [devhotteok/TwitchLink#77]
가끔 무한 로딩이걸리고 예약녹화가 중간에 끈김니다.  
1)  문제가 발생하면 예약녹화중이던 모든 방송이 녹화가 끈기지만 프로그램상으로는 계속 녹화하고있는듯이 아래바는 움직입니다.
2)  이 증상이발생하면 해당방송이 종료돼도 계속 녹화중인 상태로나옵니다. 
3)  수동으로 종료해주지않으면 다음번 방송이 시작되도 더이상 녹화는 되지않지만 계속 녹화있는것처럼나옵니다.
4) 실제 파일은 해당 증상이 발생한 시점에 멈춰있고 더이상 녹화가되지않습니다.
5) vpn을 사용하고있어 vpn으로인한 끈김문제로 의심하였으나 실제로 vpn이 끊기면 정상적인경우 녹화가 종료됐다가 새로 녹화를 시작하더군요.
6) 처음엔 어쩌다 발생한 증상으로알았으나 부정기적으로 해당 증상이 반복되는것으로보아 확인이필요해보여 리포팅해봅니다.

**Comment by devhotteok** [comment]
Duplicate of #68
