### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by gimmanggo** [devhotteok/TwitchLink#8]
트위치 링크를 잘 쓰고있는 사람입니다.
덕분에 다시보기 사라질 걱정없이 방송 잘 보고있는데 단 한가지 아쉬운 점이 요새 실시간 녹화를 하면 한번 이상은 무조건 실시간 방송이 끝나지 않았어도 완료가 됩니다. 특정 키를 누르면 그런 것인가 해서 키보드를 건들여보지않았는데도 여전히 같은 증상이 발현됩니다.
문의 내역을 찾아보니 저 말고도 다른 사람도 같은 증상이 있는 것 같은데 혹시 이 증상을 해결하기위한 방안이 있을까요?
항상 감사합니다

추가로 트위치 링크의 변동사항이 있을시 자동으로 업데이트가 되나요? 아니면 지우고 다시 깔아야 하나요?

Translate

I'm using Twitch link well.
Thanks to this, I'm watching the broadcast well without worrying about the replay disappearing, but the only regret is that if I record it in real time these days, it will be completed even if the real-time broadcast is not over. 
I didn't touch the keyboard to see if this symptom appears when a specific key is pressed, but the same symptoms still appear.
Looking at the details of the issue, it seems that other people besides me have the same symptoms, so is there a way to solve this symptom?
Thank you always.

Just one more thing If there is any additional change in the Twitch link, will it be automatically updated? Or should I erase it and put it back on?

**Comment by devhotteok** [comment]
Interruptions in live downloads are one of the problems of broadcast, transmission, and your personal network.
Currently, if the download is interrupted or complete, you will be notified.

You will be notified when TwitchLink has an update.
The update overwrites the previous version, there is no need to delete the previous version.
