### ISSUE TITLE
A network error has occured

### ISSUE THREAD

**Issue by nameless01234567** [devhotteok/TwitchLink#83]
I was going to use TwitchLink today and as soon as I opened a channel the "A network error has occured" appeared and going into the videos it said "A temporary error has occured. Please try again later.". Refreshing resulted in the same messeges

Opening the videos on twitch seems to be working so I don't think its a internet issue.

Version 2.3.2

**Comment by anivire** [comment]
Same problem

**Comment by SgtKeeneye** [comment]
I am also having this issue

**Comment by grisottomaximo** [comment]
Same issue here

**Comment by getFran** [comment]
Same here

**Comment by techiolo** [comment]
same. can't download anymore

**Comment by Ur3rdIMcFly** [comment]
I assumed it was temporary. Then I thought maybe antivirus ate it when I did a scan, so I reinstalled. Windows warned me before installing, installed anyway. Still doesn't work.

**Comment by berdie921024** [comment]
same.

**Comment by slamdunk95** [comment]
When doing a search using the channel ID I get the "Network Error" popup, after closing the popup, the Stream tab works fine, it's just the Clip/Video tab that doesn't work for me. If I do a search for individual VODs or clips using the URL, I get no error and I'm able to download without any issues.

Version 2.3.2

**Comment by berdie921024** [comment]
> 

its work thx

**Comment by devhotteok** [comment]
A temporary action has been taken on the issue. There will be a fundamental fix for this issue in the next update.

**Comment by devhotteok** [comment]
Closed with commit 1b2f4e038d0c3940c1ca79e48fd835521f572195
