### ISSUE TITLE
Settings not saved?

### ISSUE THREAD

**Issue by slamdunk95** [devhotteok/TwitchLink#85]
Since last restarting TwitchLink, I had made a lot of changes in the app, like adding channel bookmarks, setting up scheduled downloads and logging in with an account that had a Twitch Turbo subscription. However, my windows PC decided to do an update and restarted in the middle of the night, and all of those changes were undone and had reverted to when I last closed the app. This can be recreated if you make any changes and then go into task manager, highlight TwitchLink and click "End Task", upon restarting the app any changes made will be undone.

**Comment by skyfox1977** [comment]
I can confirm, I have the same issue.
