### ISSUE TITLE
It would be nice to have a batch download function for clips

### ISSUE THREAD

**Issue by sizzl3** [devhotteok/TwitchLink#87]
There are quite a few extensions for downloading clips from Twitch, 
but Almost all of them are available for download only one at a time, 
and often fail to pick up a title or date.
If the developer can afford it, I hope that the clip batch download function will be added.
It would be great if the date/title were labeled together.

I always use the program well and sometimes I donate a small amount.
Thank you.

**Comment by devhotteok** [comment]
Duplicate of #38
