### ISSUE TITLE
3번 이상 다운로드시 다운로드 99%에서 멈춤

### ISSUE THREAD

**Issue by asd1029** [devhotteok/TwitchLink#9]
다시보기를 다운로드하는데 2번까지는 잘만 다운 되다가 3번째 부터 다운로드가 99%에서 멈춥니다 
그래서 프로그램을 지웠다 다시 다운해야하는 번거로움이 있습니다

**Comment by asd1029** [comment]
> 다시보기를 다운로드하는데 2번까지는 잘만 다운 되다가 3번째 부터 다운로드가 99%에서 멈춥니다
그래서 프로그램을 자꾸 지웠다 다운해야하는 번거로움이 있습니다

**Comment by devhotteok** [comment]
Closed due to inactivity.
