### ISSUE TITLE
connecting issue

### ISSUE THREAD

**Issue by gtskks** [devhotteok/TwitchLink#92]
![conne](https://github.com/devhotteok/TwitchLink/assets/113231866/8a0f2bab-8a97-44b1-8996-a3e04c93914e)

Sometimes I get the message Connecting as shown in the screenshot.

Sometimes I can close the program and restart it, sometimes not.

Same goes for deleting and re-adding. 

The streamer starts streaming, but doesn't record, and I have to refresh or

I turn it off and on again and it starts recording.

My recording list numbers total 62, but I don't record all 62 people.

It's usually between 5 and 10.

Would having too many lists be a problem?

**Comment by devhotteok** [comment]
Please attach the log file so I can figure out the reason.
But it looks like you have too many connected channels.

**Comment by devhotteok** [comment]
Closed due to inactivity.
