### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by LeviKK999** [devhotteok/TwitchLink#94]
5월 31일까지 잘 사용하고 있었는데
6월 1일 새로운 업데이트가 있다고 해서, 기존에 있던 프로그램을 삭제하고, 새로운 버전을 다운 받으려니까 이러한 메세지가 계속 나옵니다.
원래 사용하던 버전을 다운 받아도 또 이렇게 나옵니다.
어떤 문제인가요?
![2](https://github.com/devhotteok/TwitchLink/assets/81400263/7422baf2-a5f7-4c32-9397-6f8e955c614b)
![1](https://github.com/devhotteok/TwitchLink/assets/81400263/c1550bb8-5c19-413b-b509-1790a906e2b5)

**Comment by booksky91** [comment]
> 

https://github.com/streamlink/streamlink/issues/5370

**Comment by devhotteok** [comment]
Try the following.
1. Uninstall the program
2. Download the new installer
3. Reinstall the program
