### ISSUE TITLE
Questions about scheduled downloads

### ISSUE THREAD

**Issue by sososo22** [devhotteok/TwitchLink#99]
현재 최신버전 사용중이구요

예약목록이 50개가 넘어가는순간에 녹화중인 다른 프로세스가 

녹화시간은 멈춰버리고 용량은 증가하는현상이 발생하네요

혹시 예약숫자를 늘리는게 가능할까요? 

예약목록에 넣어놓고 필요한 스트리밍만 녹화 on/off 하면서 사용중인데

목록 50개가 의도하신 제한숫자인지 아니면 늘릴수있는건지 문의드립니다.

**Comment by Dev-Pixel-www** [comment]
샌드박스 소프트웨어를 사용하세요.

**Comment by devhotteok** [comment]
It seems that the number of reserved downloads has exceeded the limit that your hardware or network can handle.
